// generated by unplugin-vue-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CustomSpinner: typeof import('D:/personal projects/coollabs-extension/src/components/CustomSpinner.vue')['default']
    LoginForm: typeof import('D:/personal projects/coollabs-extension/src/components/LoginForm.vue')['default']
  }
}

export { }
